/**
 * Seed the drugs catalog from a CSV (playbook Phase 1).
 *
 *   npm run seed                       # uses drugs.sample.csv
 *   npm run seed path/to/eda.csv       # uses your own export
 *
 * Expects env: NEXT_PUBLIC_SUPABASE_URL, SUPABASE_SERVICE_ROLE_KEY.
 * The CSV is normalized to: brand_name, brand_name_ar, generic_name,
 * active_ingredient, strength, form, eda_reg_no. search_text is generated by
 * the DB, so we don't compute it here.
 */
import { readFileSync } from "node:fs";
import { resolve } from "node:path";
import { parse } from "csv-parse/sync";
import { createClient } from "@supabase/supabase-js";

const url = process.env.NEXT_PUBLIC_SUPABASE_URL;
const key = process.env.SUPABASE_SERVICE_ROLE_KEY;

if (!url || !key) {
  console.error("Missing NEXT_PUBLIC_SUPABASE_URL or SUPABASE_SERVICE_ROLE_KEY.");
  process.exit(1);
}

const csvPath = resolve(process.argv[2] ?? "supabase/seed/drugs.sample.csv");
const VALID_FORMS = new Set([
  "tablet", "syrup", "capsule", "cream", "drops", "injection", "inhaler", "other",
]);

function clean(v: string | undefined): string | null {
  const s = (v ?? "").trim();
  return s.length ? s : null;
}

async function main() {
  const raw = readFileSync(csvPath, "utf8");
  const rows = parse(raw, { columns: true, skip_empty_lines: true, trim: true }) as Record<string, string>[];

  const drugs = rows
    .map((r) => {
      const brand = clean(r.brand_name);
      const ingredient = clean(r.active_ingredient) ?? clean(r.generic_name);
      if (!brand || !ingredient) return null;
      const form = (clean(r.form) ?? "other").toLowerCase();
      return {
        brand_name: brand,
        brand_name_ar: clean(r.brand_name_ar),
        generic_name: clean(r.generic_name),
        active_ingredient: ingredient,
        strength: clean(r.strength),
        form: VALID_FORMS.has(form) ? form : "other",
        eda_reg_no: clean(r.eda_reg_no),
      };
    })
    .filter((d): d is NonNullable<typeof d> => d !== null);

  console.log(`Parsed ${drugs.length} drugs from ${csvPath}`);

  const supabase = createClient(url!, key!, { auth: { persistSession: false } });

  // Insert in chunks so large EDA exports don't blow the request size.
  const CHUNK = 500;
  for (let i = 0; i < drugs.length; i += CHUNK) {
    const batch = drugs.slice(i, i + CHUNK);
    const { error } = await supabase.from("drugs").insert(batch);
    if (error) {
      console.error(`Insert failed at chunk ${i}:`, error.message);
      process.exit(1);
    }
    console.log(`Inserted ${Math.min(i + CHUNK, drugs.length)}/${drugs.length}`);
  }

  console.log("✅ Seed complete.");
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
